### ISSUE TITLE
Mobs name is heart

### ISSUE THREAD

**Issue by eliyash31** [sb2bg/CustomDeathMessages#1]
Hello how can I fix this? instead of getting the name of the mob, it just displays the hearts same as in the console log..

https://imgur.com/f5Rtf9c

I am using BeautyIndicator plugin to put hearts UI on mobs health

**Comment by sb2bg** [comment]
Plugins like those change the entities display name to hearts, and that's how they display their health. I can look into seeing if there's a way to bypass this, but in the meantime I suggest turning off the entity name messages in config.

**Comment by Poweringg** [comment]
> Plugins like those change the entities display name to hearts, and that's how they display their health. I can look into seeing if there's a way to bypass this, but in the meantime I suggest turning off the entity name messages in config.


You should make condition - if entity has in name ♥ symbol, then show its regular name(eg.Zombie) or show regular message (from.. eg. zombie-messages). 

Hearts in chat are annoying, thanks. :D

**Comment by Legoman99573** [comment]
In my fork/maintenance branch, I assume this comes from mcMMO and if the entity contains ❤ and mcMMO is running, it will no longer use custom messaging. Having mcMMO disabled or removed will display the ❤ as expected unless this comes from another plugin that renames mobs.
