### ISSUE TITLE
[Suggestion] Make killer name becaused killed by crystal

### ISSUE THREAD

**Issue by ghost** [sb2bg/CustomDeathMessages#10]
like this:   &3%player%&4 was blown up by &3%killer%&4 with an &6end crystal

end-crystal-messages:
- "&c%victim% &egot pieced by an &d&lEnd Crystal"
- "&c%victim% &egot blown up by an &d&lEnd Crystal"

**Comment by sb2bg** [comment]
Have you tried doing it? I believe it may work?
