### ISSUE TITLE
%kill-weapon% ?

### ISSUE THREAD

**Issue by ghost** [sb2bg/CustomDeathMessages#15]
[22:12:21 INFO]: esrtk_wiitap was EZ clapped by kakih using %kill-weapon%

**Comment by sb2bg** [comment]
Interesting.

1. Any error messages?
2. Is 'enable-item-on-hover' enabled?
3. Do you know what item the player was killed by?

**Comment by ghost** [comment]
> Interesting.
> 
>     1. Any error messages?
>    no
>     2. Is 'enable-item-on-hover' enabled?
>   false
>     3. Do you know what item the player was killed by?
     no

**Comment by ghost** [comment]
i just see in console this

**Comment by ghost** [comment]
iron_axe my player says  

[17:58:34 INFO]: AtTheMoro1 was slain by Modestoo using %kill-weapon%

**Comment by sb2bg** [comment]
Unable to reproduce. Nobody else has this issue, stopped investigating
