### ISSUE TITLE
[Feature Request] Disable Messages

### ISSUE THREAD

**Issue by murat716** [sb2bg/CustomDeathMessages#2]
global-pvp-death-messages: []
melee-death-messages: []

I want to turn off pvp messages, but when I set it like this, the console gives an error. Vanilla messages are much better I don't want to change that.

Paper-1.16.3
Latest CDM

**Comment by sb2bg** [comment]
I don't think it would be a good idea to have individual sections that could be disabled, instead you can replace the custom messages with the vanilla messages you'd like.
