### ISSUE TITLE
Plugin not loading. 

### ISSUE THREAD

**Issue by look-a-furry** [sb2bg/CustomDeathMessages#3]
So, I just downloaded this plug-in from spigotmc.org and It's not working. When I do a /reload it gives me the following error message:
[Server thread/ERROR]: Error occurred while enabling CustomDeathMessages v1.7.2 (Is it up to date?) 

It obviously is up to date as I literally just downloaded it.

Edit: I'm on 1.16.5

![imagen](https://user-images.githubusercontent.com/58516910/112759848-25457300-8ff5-11eb-86e8-7b924822d316.png)

**Comment by sb2bg** [comment]
can you give the full error info? or is that all it says
