### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by ghost** [sb2bg/CustomDeathMessages#4]
Hello, I love your plugin! I just want to ask you, is there any option to configure message "You have no bed or charged respawn anchor, or it was obstructed"? I can not find it.

**Comment by sb2bg** [comment]
> Hello, I love your plugin! I just want to ask you, is there any option to configure message "You have no bed or charged respawn anchor, or it was obstructed"? I can not find it. 
> 
> 

Yes, the display name placeholder *should* include the prefix. That's depends on how luckperms implemented it. And for the respawns, it most likely won't be added because it's not a death message and I also don't think it's natively overridable. I can see though ;)

**Comment by sb2bg** [comment]
I'll leave this open to see if you have any issues with the prefix

**Comment by ghost** [comment]
Thank you! BTW I downloaded this plugin to translate death messages into Czech language and it looks kinda weird with that, but anyway thank you!
![2021-05-15_01 21 19](https://user-images.githubusercontent.com/74290177/118340487-1c185300-b51c-11eb-885c-b02df52a04f4.png)

**Comment by sb2bg** [comment]
> Thank you! BTW I downloaded this plugin to translate death messages into Czech language and it looks kinda weird with that, but anyway thank you!
> 
> ![2021-05-15_01 21 19](https://user-images.githubusercontent.com/74290177/118340487-1c185300-b51c-11eb-885c-b02df52a04f4.png)
> 
> 

of course :) as for the weird looking characters, could it be a minecraft thing? my plugin doesn't do anything special to characters, so i don't really know what's up with that
