### ISSUE TITLE
Netherite Items uses "melee-death-messages:" messages

### ISSUE THREAD

**Issue by Shrouzed** [sb2bg/CustomDeathMessages#5]
Hello there,

So we noticed that killing someone with a netherite sword actually use "melee-death-messages:" messages instead of "global-pvp-death-messages:" messages.

All settings are set to true in the config file and other weapons work fine. So I imagine it's an issue with netherite.

Version: Paper version git-Paper-722 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugin version: 1.7.2

**Comment by sb2bg** [comment]
Gosh, this is an old one. Fixed with latest commit haha
