### ISSUE TITLE
[Suggestion] Cooldown to death messages

### ISSUE THREAD

**Issue by ghost** [sb2bg/CustomDeathMessages#7]
+ Set the cooldown for player deaths to prevent spam
+ Cooldown time in seconds
+ Console messages ignore cooldowns and will still send to console
+ Default: 0 (disabled)
+ Cooldown: 10

like this

**Comment by sb2bg** [comment]
I like this idea a lot. Would it only prevent death messages of the same player being sent, or all death messages?

**Comment by ghost** [comment]
> I like this idea a lot. Would it only prevent death messages of the same player being sent, or all death messages?

for player, for example i have /kill command and players can spam chat with deaths

**Comment by sb2bg** [comment]
Got it. Thanks for the suggestion. Definitely expect this in the next update, coming soon.
